# config/services.yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
#  Paco\CustomPacoBundle\:
#    resource: '../../../src/*'
#    exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php}'

  #message provider as service
  custom_paco_bundle.meeting_message_provider:
    class: Paco\CustomPacoBundle\MeetingMessageProvider
    public: true
    tags:
      - { name: 'paco.meeting_provider', priority: 10 }

  # the id is not a class, so it won't be used for autowiring
  custom_paco_bundle.paco_number_generator:
    class: Paco\CustomPacoBundle\PacoNumberGenerator
    #arguments: ['@custom_paco_bundle.meeting_message_provider']
    arguments:
      - !tagged_iterator paco.meeting_provider
    public: true

  # but this fixes it!
  # the ``app.rot13.transformer`` service will be injected when
  # an ``App\Util\Rot13Transformer`` type-hint is detected
  Paco\CustomPacoBundle\PacoNumberGenerator: '@custom_paco_bundle.paco_number_generator'

  Paco\CustomPacoBundle\MeetingMessageProvider: '@custom_paco_bundle.meeting_message_provider'

  #controller as service
  #When you create a controller in a reusable bundle, the best practice is to register your
  #controller as a proper service and use dependency injection to get anything you need
  custom_paco_bundle.number_generator_api_controller:
      class: Paco\CustomPacoBundle\Controller\NumberGeneratorApiController
      arguments: ['@custom_paco_bundle.paco_number_generator','@event_dispatcher']
      public: true
      calls:
        -   [ setContainer,["@service_container"] ]
      tags:
        - name: 'container.service_subscriber'